/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as DemoDbTodosRouteImport } from './routes/demo.db.todos'
import { Route as DemoDbSimpleListRouteImport } from './routes/demo.db.simple-list'
import { Route as ApiElectricShapeRouteImport } from './routes/api.electric.$shape'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDbTodosRoute = DemoDbTodosRouteImport.update({
  id: '/demo/db/todos',
  path: '/demo/db/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDbSimpleListRoute = DemoDbSimpleListRouteImport.update({
  id: '/demo/db/simple-list',
  path: '/demo/db/simple-list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElectricShapeRoute = ApiElectricShapeRouteImport.update({
  id: '/api/electric/$shape',
  path: '/api/electric/$shape',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/electric/$shape': typeof ApiElectricShapeRoute
  '/demo/db/simple-list': typeof DemoDbSimpleListRoute
  '/demo/db/todos': typeof DemoDbTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/electric/$shape': typeof ApiElectricShapeRoute
  '/demo/db/simple-list': typeof DemoDbSimpleListRoute
  '/demo/db/todos': typeof DemoDbTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/electric/$shape': typeof ApiElectricShapeRoute
  '/demo/db/simple-list': typeof DemoDbSimpleListRoute
  '/demo/db/todos': typeof DemoDbTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/electric/$shape'
    | '/demo/db/simple-list'
    | '/demo/db/todos'
    | '/demo/form/address'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/electric/$shape'
    | '/demo/db/simple-list'
    | '/demo/db/todos'
    | '/demo/form/address'
  id:
    | '__root__'
    | '/'
    | '/api/electric/$shape'
    | '/demo/db/simple-list'
    | '/demo/db/todos'
    | '/demo/form/address'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiElectricShapeRoute: typeof ApiElectricShapeRoute
  DemoDbSimpleListRoute: typeof DemoDbSimpleListRoute
  DemoDbTodosRoute: typeof DemoDbTodosRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/db/todos': {
      id: '/demo/db/todos'
      path: '/demo/db/todos'
      fullPath: '/demo/db/todos'
      preLoaderRoute: typeof DemoDbTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/db/simple-list': {
      id: '/demo/db/simple-list'
      path: '/demo/db/simple-list'
      fullPath: '/demo/db/simple-list'
      preLoaderRoute: typeof DemoDbSimpleListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/electric/$shape': {
      id: '/api/electric/$shape'
      path: '/api/electric/$shape'
      fullPath: '/api/electric/$shape'
      preLoaderRoute: typeof ApiElectricShapeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiElectricShapeRoute: ApiElectricShapeRoute,
  DemoDbSimpleListRoute: DemoDbSimpleListRoute,
  DemoDbTodosRoute: DemoDbTodosRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
