/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as ApiFilesIndexRouteImport } from './routes/api/files/index'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as ApiFilesIdRouteImport } from './routes/api/files/$id'
import { Route as ApiElectricShapeRouteImport } from './routes/api/electric.$shape'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AuthedDemoDbTodosRouteImport } from './routes/_authed/demo/db.todos'
import { Route as AuthedDemoDbSimpleListRouteImport } from './routes/_authed/demo/db.simple-list'
import { Route as AuthedDemoDbFilesRouteImport } from './routes/_authed/demo/db.files'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesIndexRoute = ApiFilesIndexRouteImport.update({
  id: '/api/files/',
  path: '/api/files/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesIdRoute = ApiFilesIdRouteImport.update({
  id: '/api/files/$id',
  path: '/api/files/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElectricShapeRoute = ApiElectricShapeRouteImport.update({
  id: '/api/electric/$shape',
  path: '/api/electric/$shape',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDemoDbTodosRoute = AuthedDemoDbTodosRouteImport.update({
  id: '/demo/db/todos',
  path: '/demo/db/todos',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDemoDbSimpleListRoute = AuthedDemoDbSimpleListRouteImport.update({
  id: '/demo/db/simple-list',
  path: '/demo/db/simple-list',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDemoDbFilesRoute = AuthedDemoDbFilesRouteImport.update({
  id: '/demo/db/files',
  path: '/demo/db/files',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/electric/$shape': typeof ApiElectricShapeRoute
  '/api/files/$id': typeof ApiFilesIdRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/api/files/': typeof ApiFilesIndexRoute
  '/demo/db/files': typeof AuthedDemoDbFilesRoute
  '/demo/db/simple-list': typeof AuthedDemoDbSimpleListRoute
  '/demo/db/todos': typeof AuthedDemoDbTodosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/electric/$shape': typeof ApiElectricShapeRoute
  '/api/files/$id': typeof ApiFilesIdRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/api/files': typeof ApiFilesIndexRoute
  '/demo/db/files': typeof AuthedDemoDbFilesRoute
  '/demo/db/simple-list': typeof AuthedDemoDbSimpleListRoute
  '/demo/db/todos': typeof AuthedDemoDbTodosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/electric/$shape': typeof ApiElectricShapeRoute
  '/api/files/$id': typeof ApiFilesIdRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/api/files/': typeof ApiFilesIndexRoute
  '/_authed/demo/db/files': typeof AuthedDemoDbFilesRoute
  '/_authed/demo/db/simple-list': typeof AuthedDemoDbSimpleListRoute
  '/_authed/demo/db/todos': typeof AuthedDemoDbTodosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/api/auth/$'
    | '/api/electric/$shape'
    | '/api/files/$id'
    | '/demo/form/address'
    | '/api/files/'
    | '/demo/db/files'
    | '/demo/db/simple-list'
    | '/demo/db/todos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/api/auth/$'
    | '/api/electric/$shape'
    | '/api/files/$id'
    | '/demo/form/address'
    | '/api/files'
    | '/demo/db/files'
    | '/demo/db/simple-list'
    | '/demo/db/todos'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/api/auth/$'
    | '/api/electric/$shape'
    | '/api/files/$id'
    | '/demo/form/address'
    | '/api/files/'
    | '/_authed/demo/db/files'
    | '/_authed/demo/db/simple-list'
    | '/_authed/demo/db/todos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiElectricShapeRoute: typeof ApiElectricShapeRoute
  ApiFilesIdRoute: typeof ApiFilesIdRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  ApiFilesIndexRoute: typeof ApiFilesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/': {
      id: '/api/files/'
      path: '/api/files'
      fullPath: '/api/files/'
      preLoaderRoute: typeof ApiFilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$id': {
      id: '/api/files/$id'
      path: '/api/files/$id'
      fullPath: '/api/files/$id'
      preLoaderRoute: typeof ApiFilesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/electric/$shape': {
      id: '/api/electric/$shape'
      path: '/api/electric/$shape'
      fullPath: '/api/electric/$shape'
      preLoaderRoute: typeof ApiElectricShapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/demo/db/todos': {
      id: '/_authed/demo/db/todos'
      path: '/demo/db/todos'
      fullPath: '/demo/db/todos'
      preLoaderRoute: typeof AuthedDemoDbTodosRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/demo/db/simple-list': {
      id: '/_authed/demo/db/simple-list'
      path: '/demo/db/simple-list'
      fullPath: '/demo/db/simple-list'
      preLoaderRoute: typeof AuthedDemoDbSimpleListRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/demo/db/files': {
      id: '/_authed/demo/db/files'
      path: '/demo/db/files'
      fullPath: '/demo/db/files'
      preLoaderRoute: typeof AuthedDemoDbFilesRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDemoDbFilesRoute: typeof AuthedDemoDbFilesRoute
  AuthedDemoDbSimpleListRoute: typeof AuthedDemoDbSimpleListRoute
  AuthedDemoDbTodosRoute: typeof AuthedDemoDbTodosRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDemoDbFilesRoute: AuthedDemoDbFilesRoute,
  AuthedDemoDbSimpleListRoute: AuthedDemoDbSimpleListRoute,
  AuthedDemoDbTodosRoute: AuthedDemoDbTodosRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiElectricShapeRoute: ApiElectricShapeRoute,
  ApiFilesIdRoute: ApiFilesIdRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  ApiFilesIndexRoute: ApiFilesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
